---

name: Build Edge
"on":
  push:
    paths:
      - "app/**"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
      - ".gitea/workflows/build-edge.yaml"
  pull_request:
    paths:
      - "app/**"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
      - ".gitea/workflows/build-edge.yaml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Setup keystore
        run: |
          echo "${{ secrets.KEY_STORE }}" | base64 -d > release-key.jks
          echo "KEYFILE=$(pwd)/release-key.jks" >> $GITEA_ENV

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            tools platform-tools platforms;android-36

      - name: Build Debug
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
          KEY_STORE_PASS: ${{ secrets.KEY_STORE_PASS }}
        run: |
          ./gradlew assembleDebug \
          -Pandroid.injected.signing.store.file=$KEYFILE \
          -Pandroid.injected.signing.store.password=$KEY_STORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASS

      - name: Build Release
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASS: ${{ secrets.KEY_PASS }}
          KEY_STORE_PASS: ${{ secrets.KEY_STORE_PASS }}
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$KEYFILE \
          -Pandroid.injected.signing.store.password=$KEY_STORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASS

      - name: Publish
        run: |
          export commit=$(git rev-parse --short=6 HEAD)
          curl  \
          --user ${{ vars.maintainer }}:${{ secrets.TOKEN }} \
          --upload-file app/build/outputs/apk/edge/debug/app-edge-debug.apk \
          https://code.dawn.org.in/api/packages/${{ vars.maintainer }}/generic/helm/edge/app-edge-debug.apk
          curl  \
          --user ${{ vars.maintainer }}:${{ secrets.TOKEN }} \
          --upload-file \
          app/build/outputs/apk/edge/release/app-edge-release.apk \
          https://code.dawn.org.in/api/packages/${{ vars.maintainer }}/generic/helm/edge/app-edge-release.apk
          curl  \
          --user ${{ vars.maintainer }}:${{ secrets.TOKEN }} \
          --upload-file app/build/outputs/apk/edge/debug/app-edge-debug.apk \
          https://code.dawn.org.in/api/packages/${{ vars.maintainer }}/generic/helm/edge-$commit/app-edge-debug.apk
          curl  \
          --user ${{ vars.maintainer }}:${{ secrets.TOKEN }} \
          --upload-file \
          app/build/outputs/apk/edge/release/app-edge-release.apk \
          https://code.dawn.org.in/api/packages/${{ vars.maintainer }}/generic/helm/edge-$commit/app-edge-release.apk
